deployment:
  tasks:
    - echo "Starting deployment..."
    - cd /home/nikusoft/public_html/historical-calendar.onespect.com/beta2
    - git fetch origin
    - git reset --hard origin/main
    - echo "Deployment completed successfully!"
