deployment:
  tasks:
    - export DEPLOY_PATH=/home/nikusoft/public_html/historical-calendar.onespect.com/beta2
    - echo "Starting deployment to $DEPLOY_PATH"
    - cd $DEPLOY_PATH
    - git pull origin main
    - echo "Deployment completed on $(date)"
